### ISSUE TITLE
Unable to use persistentdatapath or edit JSON file I know exists

### ISSUE THREAD

**Issue by TKTSWalker** [LifeandStyleMedia/UniversalSave#4]
Hello, I am currently using Unity 2020.2.3f1 with Unity Bolt 1.4.15 and Universal Save v1.0.0 for Bolt. I have been using the asset for a while now but recently, I have gotten the error: Object Reference Not Set To An Instance Of An Object". I figured out that meant it didn't see any file that was being referenced so instead used the documents folder. However, i'm now trying to use Remove Universal Variable and Set Universal Variable to create a system and while I got through the persistentdatapath and the fact that "Promote To Import Path" doesn't work as well, the real problem comes when I am unable to edit the JSON file. I tried everything from dictionaries to strings and no matter what I try, I can not edit the variables within. Are there any tips onto what might be happening? I really like this system and would like to keep using it.

**Comment by MasterSubby** [comment]
Thanks for reporting. I'm glad your enjoying it. Sorry your having some trouble. I'll have to do some testing on my end. Is this occurring in the editor? Are you speaking of manually modifying the json, or using the nodes when using the JSON format simply returns null?

I'll have some time in the next few days. I'll see what I can find.

**Comment by TKTSWalker** [comment]
Its np, im happy you made such a thing and released it! Its occurring within the editor and whereas Json and Binary doesn't work, Nodes give the object exception warning! Its getting the proper data in as well if I call the variable, it just can't change the save file at all for some reason.

**Comment by MasterSubby** [comment]
Can you share a graph of how your saving, loading and getting the variables? Need to make sure it's not something on your end. This is a first report of it's kind.

**Comment by TKTSWalker** [comment]
Here are the segments where I save, get and load the variables! The Data folder is a folder that is made from Unity.
![segmentb](https://user-images.githubusercontent.com/56851930/129478486-ec3e523a-3514-4bae-b0a7-6ec6a5155429.PNG)
![segmenta](https://user-images.githubusercontent.com/56851930/129478490-feeb7959-60db-4a3e-9a93-d5227666693e.PNG)

**Comment by MasterSubby** [comment]
Thank you. Hmm nothing stands out though. What's your path like? How are you building it? You don't seem to actually be using the presistant data path from the nodes. Are you using that path from Application.persistantDataPath yourself? Curious if the path is being built correctly.

**Comment by TKTSWalker** [comment]
I am using the documents path then have \XRUIOS Data added to it before the subdirectory is created. The folder building works properly and im not using the node persistent data path as itll gove me the error which says it doesn't exist.

**Comment by MasterSubby** [comment]
I suspected something actually with the last statement. There is an appended /data/ added to the persistant path. This was once upon a time recommended in the readings I was doing while working on this specifically for iOS. I actually supposed I never checked if it exists, to create it. Not sure how that passes by my radar. I obviously tested working at some point in the past. Anyways, I will remove it, and add the ability to append the path to your liking. Simple fix on my end, so I can get to that sometime today instead of waiting.

As far as your actual data, I still do not see how it's returning nothing. I've tested on many platforms including, Android, WebGL, Windows, and the editor, every time I submit, and never experienced this. We once upon a time had 0kb JSON being returned, but that was fixed.

I'm not sure what else you can provide me, but I can't yet reproduce this behavior.

**Comment by MasterSubby** [comment]
Okay the data path has now been removed and changes populated to both branches. I am closing this, as the main issue of the persistantDataPath has been fixed. If you are still having trouble reading the data, please open another issue to track that specifically. For reference, I did a test to show it is working:

*Side note, make sure your custom path does not have an end slash. It's added on. I could probably do better at predicting these kind of things so that they don't matter at all.

![Unity_2021-08-16_01-48-32](https://user-images.githubusercontent.com/7036136/129517455-31d51831-5a11-4691-b962-ced244757141.png)

and here is the output of JSON:

```
{
    "$id": 0,
    "$type": "0|Lasm.Bolt.UniversalSaver.UniversalSave, Assembly-CSharp",
    "dataFormat": 1,
    "variables": {
        "$id": 1,
        "$type": "1|System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib",
        "comparer": {
            "$id": 2,
            "$type": "2|System.Collections.Generic.GenericEqualityComparer`1[[System.String, mscorlib]], mscorlib"
        },
        "$rlength": 1,
        "$rcontent": [
            {
                "$k": "test",
                "$v": {
                    "$id": 3,
                    "$type": "3|UnityEngine.Vector3, UnityEngine.CoreModule",
                    12,
                    1,
                    22
                }
            }
        ]
    }
}
```
